services:
  - type: static
    name: todo-frontend
    buildCommand: "npm install && npm run build"
    staticPublishPath: "./build"
    envVars:
      - key: REACT_APP_API_URL
        fromService:
          name: todo-backend
          type: web
          property: host