services:
  - type: web
    name: django-react
    env: python
    buildCommand: |
      pip install -r requirements.txt
      cd frontend
      npm install
      npm run build
      cd ..
      mkdir -p backend/static_build
      cp -R frontend/build/* backend/static_build/
      cd backend
      python manage.py collectstatic --noinput
    startCommand: |
      cd /opt/render/project/src
      gunicorn backend.backend.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: backend.backend.settings